### ISSUE TITLE
No fhir output generated after run test

### ISSUE THREAD

**Issue by thuanpv1** [LinuxForHealth/dicom-fhir-converter#2]
Hello, I am new to this python lib and have a question need your support:
1. after clone the repo and install it, i run the test as following steps:
1.1. create a new file test1.py at the root folder - the folder contains setup.py
1.2. add the following code into the test1.py :

from dicom2fhir.tests import test_dicom2fhir

test = test_dicom2fhir.testDicom2FHIR()
test.test_instance_dicom2fhir()

1.3 run it with command "python test1.py"
=> it run ok but there is no output found anywhere. 
I expected there should be a fhir json output generated somewhere.

I am not sure this is an issue or just my mistake when run the test. please help me.

Regards,
thuan.

**Comment by evbaron** [comment]
Hello, Thank you for trying out dicom-fhir-converter. 
please note that the code you posted in your ticket most likely just ran the unit tests located inside the project. The tests are just pass/fail and will not provide an output. 

under  test folder there is a directory 'resources' where you can find some samples of dicom files. Not sure how familiar you are with DICOM, but each instance is its own file. so if you have multiple instances you will have multiple files within the same directory structure. 

the code to run dicom2fhir should look something like that:
```
import os
import json
from dicom2fhir import dicom2fhir

#dicom image usually a collection of dcm files within a single directory
dcmDir = os.path.join(os.getcwd(), 'dicom2fhir', 'tests', 'resources', 'dcm-instance')

#call process dicom and specify your dicom directory -> output will be ImagingStudy FHIR resource
fhir_imaging_study = dicom2fhir.process_dicom_2_fhir(dcmDir)
#print to console
print(fhir_imaging_study.as_json())
#Or save it to file
with open ('dcm-instance.fhir.json', 'w') as f:
    json.dump(fhir_imaging_study.as_json(), f)
```

so the actual entry point is dicom2fhir.process_dicom_2_fhir
it takes a directory as a input parameter and outputs ImagingStudy. You can then either print it to a console or save it to file.

Hope it helps!

**Comment by thuanpv1** [comment]
Thanks a lot.

Regards,
Thuan
